var heading = document.getElementById('heading')
var para = document.getElementsByClassName('para')
var tags = document.getElementsByTagName('a')
var query = document.querySelector('.para')
// console.log(heading)
// console.log(para.length)
// console.log(para[0])
// console.log(para[1])
console.log(query)